// Kiểm tra vòng "lãi cao phá cầu vay → vỡ nợ → ngân hàng bóp NIM": node tools/nimtest.js
// Cặp ván cùng seed, không giai đoạn thật, không sự kiện ngẫu nhiên. Ván 2: Thống đốc giữ TCV 9,0 từ tháng 31 đến tháng 54 (khi CPI đã hạ) rồi thả về quy tắc.
global.NO_REAL = true;
const fs = require('fs'); const html = fs.readFileSync(__dirname + '/../index.html', 'utf8');
const js = html.slice(html.indexOf('<script>') + 8, html.lastIndexOf('</script>')).replace('renderStart();', '');
global.window = { devicePixelRatio: 1, addEventListener() {}, scrollTo() {} }; global.document = { querySelector() { return { innerHTML: '', querySelectorAll() { return []; } }; }, getElementById() { return null; }, querySelectorAll() { return []; }, documentElement: {}, body: { appendChild() {}, classList: { add() {}, remove() {} } }, createElement() { return { style: {}, classList: { add() {}, remove() {} }, appendChild() {}, setAttribute() {}, getContext() { return null; } }; } }; global.localStorage = { getItem() { return null; }, setItem() {} }; global.navigator = { clipboard: {} }; global.requestAnimationFrame = () => 0; global.setTimeout = () => 0; global.console.warn = () => {};
const m = {}; new Function('module', js + ';module.exports={World,MAC,setW:w=>{W=w;}};')(m); const { World, MAC, setW } = m.exports;
const f = (v, d = 2) => (v == null ? '-' : (+v).toFixed(d)); let pass = 0, fail = 0; const ok = (c, msg) => { console.log(`  ${c ? '✓' : '✗'} ${msg}`); if (c) pass++; else fail++; };
const run = (seed, months, hike) => { let s = seed; Math.random = () => { s = (s * 1103515245 + 12345) % 2147483648; return s / 2147483648; }; const W = new World('bank', 'vcb', 'real'); setW(W); W.weekly = true; W.termMonths = 0; W.randomEvents = false; const rows = [];
  for (let i = 0; i < months; i++) { if (hike && i === 30) { const S = W.sbv, d = 9.0 - S.refi; S.holdRefi = true; S.refi = 9.0; S.omo = +(S.omo + d).toFixed(2); S.disc = +(S.disc + d).toFixed(2); S.bill = +(S.bill + d).toFixed(2); S.depCap6m = +(S.depCap6m + d).toFixed(2); } if (hike && i === 54) W.sbv.holdRefi = false;
    W.aiPolicy(W.player); for (let k = 0; k < 4; k++) { W.pendingEvent = null; W.weekStep(); W.pendingEvent = null; }
    const K = W.market, M = W.macro; const al = W.banks.filter(b => !b.dead); const nim = W.camelsSys(al).E.nim; rows.push({ i, refi: W.sbv.refi, lend: K.lend, lendS: K.lendShort, cof: K.cof, sp: K.lend - K.cof, realS: M.realS, pain: M.pain || 0, painM: M.painM || 0, dem: K.creditDemand, cg: W.sysCreditGrowthAnn, npl: W.sysNpl() * 100, nim, nimCut: W.nimCut || 0, cpi: M.cpi, gdp: M.gdp, ledg: W.ledgerErr || 0, lsp: Math.max(...al.map(b => b.lspCut || 0)) }); }
  return { W, rows }; };
const A = run(2, 72, false), B = run(2, 72, true); const ra = A.rows, rb = B.rows;
console.log('  th  TCV   lãi vay  CPI   lãi thực  đau  tháng  cầu   TD%   NPL   biên(lend−cof)  NIM   nhường  nhường NH   | đối chứng: lãi vay  cầu   NPL   biên   NIM');
for (const i of [12, 24, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 66, 71]) { const r = rb[i], c = ra[i]; console.log('  ' + String(i + 1).padStart(2), f(r.refi, 1).padStart(5), f(r.lend).padStart(8), f(r.cpi, 1).padStart(5), f(r.realS).padStart(9), f(r.pain, 1).padStart(5), String(r.painM).padStart(5), f(r.dem).padStart(6), f(r.cg, 1).padStart(5), f(r.npl).padStart(6), f(r.sp).padStart(14), f(r.nim).padStart(6), f(r.nimCut).padStart(7), f(r.lsp).padStart(10), '   |', f(c.lend).padStart(8), f(c.dem).padStart(6), f(c.npl).padStart(6), f(c.sp).padStart(6), f(c.nim).padStart(6)); }
const painMonths = rb.filter(r => r.pain > 0).length; ok(painMonths >= 12 && ra.filter(r => r.pain > 0).length <= 6, `1. tháng lãi vay thực vượt ngưỡng ${f(MAC.lendStar + MAC.painGap, 1)}: ván tăng lãi ${painMonths}, đối chứng ${ra.filter(r => r.pain > 0).length} (mục tiêu ≥ 12 và ≤ 6)`);
const demMin = Math.min(...rb.slice(30, 54).map(r => r.dem)), demC = Math.min(...ra.slice(30, 54).map(r => r.dem)); ok(demMin <= 0.45 && demC - demMin >= 0.1, `2. cầu tín dụng thấp nhất trong 2 năm lãi cao ×${f(demMin)} so đối chứng ×${f(demC)} (mục tiêu ≤ 0,45 và thấp hơn ≥ 0,1: doanh nghiệp dừng vay; đối chứng đã ở sàn tuyến tính 0,5)`);
const cgB = rb[53].cg, cgA = ra[53].cg; ok(cgB < cgA - 3, `3. tín dụng tăng (năm hóa) tháng 54: ${f(cgB, 1)} so đối chứng ${f(cgA, 1)} (mục tiêu thấp hơn ≥ 3 điểm)`);
const nplB = Math.max(...rb.slice(36, 66).map(r => r.npl)), nplA = Math.max(...ra.slice(36, 66).map(r => r.npl)); ok(nplB - nplA >= 0.8, `4. nợ xấu đỉnh tháng 37–66: ${f(nplB)} so đối chứng ${f(nplA)} (mục tiêu cao hơn ≥ 0,8 điểm: vỡ nợ vì gánh lãi)`);
const cutMax = Math.max(...rb.map(r => r.nimCut)); ok(cutMax >= 0.5, `5. biên cho vay hệ thống nhường tối đa ${f(cutMax)} điểm (mục tiêu ≥ 0,5)`);
const spPeak = Math.max(...rb.slice(30, 38).map(r => r.sp)), spLate = rb[53].sp; ok(spPeak - spLate >= 0.4, `6. biên lãi vay − chi phí vốn: đỉnh đầu đợt ${f(spPeak)} → tháng 54 ${f(spLate)} (mục tiêu co ≥ 0,4 trong khi TCV vẫn 9: ngân hàng phải bóp NIM)`);
const nimPeak = Math.max(...rb.slice(30, 42).map(r => r.nim)), nimLate = rb[53].nim; ok(nimLate < nimPeak - 0.15, `7. NIM hệ thống: đỉnh năm lãi cao đầu ${f(nimPeak)} → tháng 54 ${f(nimLate)} (mục tiêu giảm ≥ 0,15)`);
ok(Math.max(...rb.map(r => r.lsp)) >= 0.3, `8. ngân hàng ế room tự hạ thêm lãi niêm yết tới ${f(Math.max(...rb.map(r => r.lsp)))} điểm (mục tiêu ≥ 0,3)`);
ok(Math.abs(rb[71].ledg) <= 50 && Math.abs(ra[71].ledg) <= 50, `9. sổ tiền cơ sở: ${f(rb[71].ledg, 0)} / ${f(ra[71].ledg, 0)}`);
console.log(`\nĐạt ${pass}, trượt ${fail}`);
