// Kiểm tra giai đoạn số liệu thật 12/2025–9/2026 và công tắc sự kiện ngẫu nhiên: node tools/realtest.js
const fs = require('fs'); const html = fs.readFileSync(__dirname + '/../index.html', 'utf8');
const js = html.slice(html.indexOf('<script>') + 8, html.lastIndexOf('</script>')).replace('renderStart();', '');
global.window = { devicePixelRatio: 1, addEventListener() {}, scrollTo() {} }; global.document = { querySelector() { return { innerHTML: '', querySelectorAll() { return []; } }; }, getElementById() { return null; }, querySelectorAll() { return []; }, documentElement: {}, body: { appendChild() {}, classList: { add() {}, remove() {} } }, createElement() { return { style: {}, classList: { add() {}, remove() {} }, appendChild() {}, setAttribute() {}, getContext() { return null; } }; } }; global.localStorage = { getItem() { return null; }, setItem() {} }; global.navigator = { clipboard: {} }; global.requestAnimationFrame = () => 0; global.setTimeout = () => 0; global.console.warn = () => {};
const m = {}; new Function('module', js + ';module.exports={World,REAL,REAL_N,getK:()=>KBNN_LDR,setW:w=>{W=w;}};')(m); const { World, REAL, REAL_N, getK, setW } = m.exports;
const f = (v, d = 2) => (v == null ? '-' : (+v).toFixed(d)); let pass = 0, fail = 0; const ok = (c, msg) => { console.log(`  ${c ? '✓' : '✗'} ${msg}`); if (c) pass++; else fail++; };
const run = (rnd, seed) => { let s = seed; Math.random = () => { s = (s * 1103515245 + 12345) % 2147483648; return s / 2147483648; }; const W = new World('bank', 'vcb', 'real'); setW(W); W.weekly = true; W.termMonths = 0; W.randomEvents = rnd; const rows = []; const evs = [];
  for (let i = 0; i < 36; i++) { W.aiPolicy(W.player); for (let k = 0; k < 4; k++) { W.pendingEvent = null; W.weekStep(); if (W.pendingEvent && !W.pendingEvent.reg && !/^(hike|cut)$/.test(W.pendingEvent.id)) evs.push({ m: W.month, id: W.pendingEvent.id }); /* hike/cut là thông báo quyết định lãi suất của NHNN, không phải sự kiện ngẫu nhiên */ if (W.pendingEvent && /^real_/.test(W.pendingEvent.id)) evs.push({ m: W.month, id: W.pendingEvent.id }); W.pendingEvent = null; } const r = W.hist[W.hist.length - 1]; const al = W.banks.filter(b => !b.dead); rows.push({ m: W.month, d: W.dateStr(), tt50: al.filter(b => b.tt50).length, nB: al.length, nsfr: r.nsfrSys, nsfrMin: W.sbv.nsfrMin, cpi: r.cpi, gdp: r.gdp, usd: r.usd, fed: r.fed, refi: r.refi, cg: r.cg, dep12: W.market.gt12, lend: r.lendNew, ib: r.ibON, ldrMax: W.sbv.ldrMax, mltMax: W.sbv.mltMax, kbnn: getK(), lcrEnf: W.sbv.lcrEnforced, ledg: Math.abs(r.ledgerErr || 0), shocks: r.shocks.join('|') }); }
  return { W, rows, evs }; };
const A = run(false, 1);
console.log(`ván bắt đầu ${A.rows[0].d}; số tháng có số liệu thật ${REAL_N} (${REAL[0].ym} → ${REAL[REAL_N - 1].ym})`);
console.log('tháng       CPI  thật  GDP  thật  USD    thật  TCV  tín dụng 12T  vay   LNH   sốc'); for (const r of A.rows) { const rr = REAL[r.m - 1]; console.log(r.d.padEnd(9), f(r.cpi, 1).padStart(5), rr ? f(rr.cpi, 1).padStart(5) : '    -', f(r.gdp, 1).padStart(5), rr ? f(rr.gdp, 1).padStart(5) : '    -', String(Math.round(r.usd)).padStart(6), rr ? String(rr.usd).padStart(6) : '     -', f(r.refi).padStart(5), f(r.cg, 1).padStart(6), f(r.dep12).padStart(5), f(r.lend).padStart(5), f(r.ib).padStart(5), ' ', r.shocks.slice(0, 50)); }
ok(A.rows[0].d === 'T12/2025', `1. ván bắt đầu ${A.rows[0].d} (mục tiêu T12/2025)`);
const dev = A.rows.slice(0, REAL_N).map((r, i) => Math.abs(r.cpi - REAL[i].cpi)); ok(Math.max(...dev.slice(2)) <= 0.6, `2. CPI mô phỏng lệch số thật tối đa ${f(Math.max(...dev.slice(2)), 2)} điểm từ tháng 3 (mục tiêu ≤ 0,6)`);
const devG = A.rows.slice(0, REAL_N).map((r, i) => Math.abs(r.gdp - REAL[i].gdp)); ok(Math.max(...devG.slice(2)) <= 0.6, `3. GDP lệch tối đa ${f(Math.max(...devG.slice(2)), 2)} điểm (mục tiêu ≤ 0,6)`);
ok(A.rows.slice(0, REAL_N).every(r => r.refi === 4.5), `4. TCV giữ 4,5 suốt giai đoạn thật ở chế độ ngân hàng (${A.rows.slice(0, REAL_N).map(r => r.refi).join(' ')})`);
const rndReal = A.evs.filter(e => e.m <= REAL_N && !/^real_/.test(e.id)); ok(rndReal.length === 0, `5. không có sự kiện ngẫu nhiên trong giai đoạn thật (${rndReal.length}); sự kiện thật đã ép: ${A.evs.filter(e => /^real_/.test(e.id)).length}`);
const rndAfter = A.evs.filter(e => e.m > REAL_N && !/^real_/.test(e.id)); ok(rndAfter.length === 0, `6. công tắc TẮT: không sự kiện ngẫu nhiên sau giai đoạn thật (${rndAfter.length} trong ${A.rows.length - REAL_N} tháng${rndAfter.length ? ': ' + rndAfter.map(e => e.id).join(', ') : ''})`);
const t50 = A.rows.find(r => r.d === 'T12/2026'); ok(t50 && t50.ldrMax === 85 && t50.mltMax === 30 && Math.abs(t50.kbnn - 0) < 1e-9 && !t50.lcrEnf && A.W.sbv.tt50, `7. TT50 có hiệu lực T12/2026 nhưng chưa ép ai: chuẩn hệ thống vẫn LDR ${t50 && t50.ldrMax}, SFL ${t50 && t50.mltMax}, KBNN ${t50 && t50.kbnn}, LCR bắt buộc ${t50 && t50.lcrEnf}; ngân hàng đã đăng ký sớm tại T12/2026: ${t50 && t50.tt50}/${t50 && t50.nB}`);
const t28 = A.rows.find(r => r.d === 'T10/2028'); ok(t28 && t28.tt50 === t28.nB && t28.lcrEnf && t28.nsfrMin === 90 && A.W.banks.filter(b => !b.dead).every(b => b.ldrCap() === 95 && Math.abs(b.kbnnShare() - 0.2) < 1e-9 && b.mltCap() > 100), `7b. T10/2028: mọi ngân hàng chuyển sang TT50 (${t28 && t28.tt50}/${t28 && t28.nB}): trần LDR 95, KBNN 20%, bỏ trần SFL, LCR bắt buộc ${t28 && t28.lcrEnf} (min ${A.W.sbv.lcrMin}), NSFR min ${t28 && t28.nsfrMin}`);
const adoptM = A.rows.filter(r => r.m > 1 && r.tt50 > A.rows[r.m - 2].tt50).map(r => `${r.d}: ${r.tt50}`); console.log('  · lộ trình đăng ký sớm:', adoptM.join(', ') || 'không ai đăng ký sớm'); console.log('  · NSFR hệ thống:', A.rows.filter(r => r.m % 6 === 1).map(r => `${r.d} ${f(r.nsfr, 0)}`).join(' | '));
const before = A.rows.find(r => r.d === 'T11/2026'); ok(before && before.ldrMax === 85 && before.mltMax === 30 && Math.abs(before.kbnn - 0) < 1e-9, `8. trước TT50 (T11/2026): LDR ${before && before.ldrMax}, SFL ${before && before.mltMax}, KBNN ${before && before.kbnn} (mục tiêu 85/30/0 theo TT22 và TT26)`);
const b0 = A.W.banks.map(b => `${b.code} NSFR ${f(b.nsfr().nsfr, 0)} LEV ${f(b.lev(), 1)} LCR ${f(b.lcr().lcr, 0)}`); console.log('  · cuối ván:', b0.join(' · '));
ok(Math.max(...A.rows.map(r => r.ledg)) < 100, `9. sổ tiền cơ sở lệch tối đa ${Math.round(Math.max(...A.rows.map(r => r.ledg)))}`);
const B = run(true, 1); const rndB = B.evs.filter(e => e.m > REAL_N && !/^real_/.test(e.id)); console.log(`  · công tắc BẬT: ${rndB.length} sự kiện ngẫu nhiên sau giai đoạn thật trong ${B.rows.length - REAL_N} tháng (${rndB.map(e => e.id).join(', ') || 'không'}); trong giai đoạn thật ${B.evs.filter(e => e.m <= REAL_N && !/^real_/.test(e.id)).length}`);
const acts = A.W.traceLog.filter(e => e.k === 'act' && /\[Thực tế\]/.test(e.t)).map(e => e.t.slice(11, 90)); console.log('sự kiện thật:', acts.length); acts.forEach(a => console.log('   ', a));
const rel = A.W.traceLog.filter(e => e.k === 'act' && /Hết giai đoạn số liệu thật/.test(e.t)).slice(-1)[0]; console.log('kết thúc giai đoạn thật:', rel ? rel.t.slice(0, 160) : 'KHÔNG CÓ');
console.log(`\nĐạt ${pass}, trượt ${fail}`); process.exit(fail ? 1 : 0);
