// Kiểm tra đảo nợ ngầm: node tools/rolltest.js — ván ngân hàng (AI), NHNN giữ TCV; tháng 6 khủng hoảng TPDN BĐS; tháng 30–42 ép BĐS đóng băng; tháng 20 thanh tra
const fs = require('fs'); const html = fs.readFileSync(__dirname + '/../index.html', 'utf8');
const js = html.slice(html.indexOf('<script>') + 8, html.lastIndexOf('</script>')).replace('renderStart();', '');
global.window = { devicePixelRatio: 1, addEventListener() {}, scrollTo() {} }; global.document = { querySelector() { return { innerHTML: '', querySelectorAll() { return []; } }; }, getElementById() { return null; }, querySelectorAll() { return []; }, documentElement: {}, body: { appendChild() {}, classList: { add() {}, remove() {} } }, createElement() { return { style: {}, classList: { add() {}, remove() {} }, appendChild() {}, setAttribute() {}, getContext() { return null; } }; } }; global.NO_REAL = true; /* kiểm thử cơ chế: không qua giai đoạn số liệu thật */ global.localStorage = { getItem() { return null; }, setItem() {} }; global.navigator = { clipboard: {} }; global.requestAnimationFrame = () => 0; global.setTimeout = () => 0; global.console.warn = () => {};
const m = {}; new Function('module', js + ';module.exports={World,EVENTS:(typeof EVENTS!=="undefined"?EVENTS:null),setW:w=>{W=w;}};')(m); const { World, EVENTS, setW } = m.exports;
let s = +(process.env.SEED || 1); Math.random = () => { s = (s * 1103515245 + 12345) % 2147483648; return s / 2147483648; };
const W = new World('bank', 'vcb', 'real'); setW(W); W.weekly = true; W.termMonths = 0; W.sbv.holdRefi = true;
const f = (v, d = 2) => (v == null ? '-' : (+v).toFixed(d)); let pass = 0, fail = 0; const ok = (c, msg) => { console.log(`  ${c ? '✓' : '✗'} ${msg}`); if (c) pass++; else fail++; };
const rows = []; const step = () => { W.aiPolicy(W.player); for (let k = 0; k < 4; k++) { W.pendingEvent = null; W.weekStep(); W.pendingEvent = null; } const r = W.hist[W.hist.length - 1]; rows.push({ m: W.month, roll: r.rollSys, npl: r.npl, nplT: r.nplTrue, re: W.macro.re, resid: Math.abs(r.bs.resid), ledg: Math.abs(r.ledgerErr || 0), cg: r.cg, banks: W.banks.filter(b => !b.dead).map(b => { const h = b.hist[b.hist.length - 1]; return { code: b.code, rollSh: h.rollSh, cap: h.rollCapM, fail: h.rollFailM, npl: h.nplG, nplT: h.nplTrue, prem: h.rollPrem, nii: h.nii }; }) }); };
for (let i = 0; i < 6; i++) step();
W.addShock({ name: 'Khủng hoảng TPDN BĐS', left: 12, re: 2.5, reHeat: -1, dep: 2, demand: 0.85, ib: 1.0 }); W.macro.re -= 0.5; console.log(`[tháng 6] khủng hoảng TPDN BĐS, BĐS ${f(W.macro.re)}`);
let insp = null; for (let i = 6; i < 42; i++) { step(); if (W.month === 20 && EVENTS) { const ev = EVENTS.find(e => e.id === 'inspect'); const before = W.banks.map(b => ({ code: b.code, g3: b.book.re.g3 + b.book.corp.g3, roll: b.rollShare() })); ev.apply(W); insp = W.banks.map((b, i) => ({ code: b.code, dG3: b.book.re.g3 + b.book.corp.g3 - before[i].g3, roll0: before[i].roll, roll1: b.rollShare() })); console.log('[tháng 20] thanh tra NHNN: ' + insp.filter(x => x.dG3 > 1).map(x => `${x.code} đảo ${f(x.roll0, 1)}→${f(x.roll1, 1)}% (+${Math.round(x.dG3)} tỷ nhóm 3)`).join(', ')); } if (W.month >= 30) W.macro.re = Math.min(W.macro.re, 0.45); }
const at = mm => rows.find(r => r.m === mm);
console.log('tháng  đảo%  NPL  NPL thật  BĐS   tín dụng'); for (const r of rows) if (r.m % 3 === 0) console.log(String(r.m).padStart(5), f(r.roll, 1).padStart(5), f(r.npl, 1).padStart(5), f(r.nplT, 1).padStart(8), f(r.re).padStart(6), f(r.cg, 1).padStart(8));
const peak = rows.slice(6, 19).reduce((a, r) => Math.max(a, r.roll), 0); ok(peak >= 1.5, `1. đảo nợ ngầm hệ thống đạt ${f(peak, 1)}% dư nợ trong 12 tháng sau sốc (mục tiêu ≥ 1,5)`);
const r18 = at(18); ok(r18.nplT - r18.npl >= 1, `2. tháng 18: NPL báo cáo ${f(r18.npl, 1)} vs bản chất ${f(r18.nplT, 1)} (chênh ≥ 1 điểm)`);
const hi = r18.banks.filter(b => b.rollSh >= 2.5); for (const b of hi.slice(0, 4)) { const cap = rows.filter(r => r.m > 6 && r.m <= 18).reduce((a, r) => a + ((r.banks.find(x => x.code === b.code) || {}).cap || 0), 0); ok(cap > 0 && b.npl < b.nplT, `3. ${b.code}: đảo ${f(b.rollSh, 1)}% dư nợ, phụ trội bq +${f(b.prem, 1)}, lãi nhập gốc 12 tháng ${Math.round(cap)} tỷ (vào thu nhập, không vào tiền), NPL ${f(b.npl, 1)} vs bản chất ${f(b.nplT, 1)}`); }
if (insp) ok(insp.some(x => x.dG3 > 1), `4. thanh tra phân loại lại 50% phần đảo vào nhóm 3 ở ${insp.filter(x => x.dG3 > 1).length} ngân hàng`);
const r30 = at(30), r42 = at(42); const failF = rows.filter(r => r.m > 30 && r.m <= 42).reduce((a, r) => a + r.banks.reduce((x, b) => x + (b.fail || 0), 0), 0), failB = rows.filter(r => r.m > 18 && r.m <= 30).reduce((a, r) => a + r.banks.reduce((x, b) => x + (b.fail || 0), 0), 0); const loans = W.sysLoans(); ok(r42.roll <= r30.roll - 0.5 && failF / loans * 100 >= 0.5 && failF > failB, `5. BĐS đóng băng (BĐS ${f(r42.re)}) tháng 30→42: đảo ${f(r30.roll, 1)} → ${f(r42.roll, 1)}%, bung thành nhóm 3 ${Math.round(failF)} tỷ (${f(failF / loans * 100, 2)}% dư nợ; 12 tháng trước đó ${Math.round(failB)}), NPL báo cáo ${f(r30.npl, 1)} → ${f(r42.npl, 1)}`);
ok(Math.max(...rows.map(r => r.resid)) < 100 && Math.max(...rows.map(r => r.ledg)) < 100, `6. đồng nhất thức bảng cân đối lệch tối đa ${Math.round(Math.max(...rows.map(r => r.resid)))}, sổ tiền cơ sở lệch ${Math.round(Math.max(...rows.map(r => r.ledg)))} (ngưỡng 100)`);
const cl = W.traceLog.filter(e => e.k === 'close' && /đảo nợ ngầm/.test(e.t)).slice(-1)[0]; console.log('log close:', cl ? cl.t.slice(cl.t.indexOf('đảo nợ ngầm'), cl.t.indexOf('đảo nợ ngầm') + 330) : 'KHÔNG CÓ');
const sb = W.traceLog.filter(e => e.k === 'sbv' && /đảo nợ ngầm/.test(e.t)).slice(-1)[0]; console.log('log sbv:', sb ? sb.t.slice(sb.t.indexOf('đảo nợ ngầm'), sb.t.indexOf('đảo nợ ngầm') + 140) : 'KHÔNG CÓ');
console.log(`\nĐạt ${pass}, trượt ${fail}`); process.exit(fail ? 1 : 0);
