// Kiểm tra dư nợ cơ cấu: node tools/rstest.js — ván ngân hàng (AI), NHNN giữ TCV; tháng 6 nổ khủng hoảng TPDN BĐS
const fs = require('fs'); const html = fs.readFileSync(__dirname + '/../index.html', 'utf8');
const js = html.slice(html.indexOf('<script>') + 8, html.lastIndexOf('</script>')).replace('renderStart();', '');
global.window = { devicePixelRatio: 1, addEventListener() {}, scrollTo() {} }; global.document = { querySelector() { return { innerHTML: '', querySelectorAll() { return []; } }; }, getElementById() { return null; }, querySelectorAll() { return []; }, documentElement: {}, body: { appendChild() {}, classList: { add() {}, remove() {} } }, createElement() { return { style: {}, classList: { add() {}, remove() {} }, appendChild() {}, setAttribute() {}, getContext() { return null; } }; } }; global.NO_REAL = true; /* kiểm thử cơ chế: không qua giai đoạn số liệu thật */ global.localStorage = { getItem() { return null; }, setItem() {} }; global.navigator = { clipboard: {} }; global.requestAnimationFrame = () => 0; global.setTimeout = () => 0; global.console.warn = () => {};
const m = {}; new Function('module', js + ';module.exports={World,MAC,setW:w=>{W=w;}};')(m); const { World, setW } = m.exports;
let s = +(process.env.SEED || 1); Math.random = () => { s = (s * 1103515245 + 12345) % 2147483648; return s / 2147483648; };
const W = new World('bank', 'vcb', 'real'); setW(W); W.weekly = true; W.termMonths = 0; W.sbv.holdRefi = true;
const f = (v, d = 2) => (v == null ? '-' : (+v).toFixed(d)); let pass = 0, fail = 0; const ok = (c, msg) => { console.log(`  ${c ? '✓' : '✗'} ${msg}`); if (c) pass++; else fail++; };
const rows = []; let formM = null, easeM = null, easeRef = null;
const step = () => { W.aiPolicy(W.player); for (let k = 0; k < 4; k++) { W.pendingEvent = null; W.weekStep(); W.pendingEvent = null; } const r = W.hist[W.hist.length - 1]; const K = W.market; rows.push({ m: W.month, prem: W.depPrem(), rs: r.rsSys, m6: K.m6_12, lt6: K.lt6, gt12: K.gt12, refi: W.sbv.refi, lend: K.lend, npl: r.npl, resid: Math.abs(r.bs.resid), ledg: r.ledgerErr, banks: W.banks.filter(b => !b.dead).map(b => ({ code: b.code, rsSh: b.rsShare(), net: b.hist[b.hist.length - 1].net, accrM: b.hist[b.hist.length - 1].rsAccrM, selfPos: b.hist[b.hist.length - 1].selfPos, m6: b.pol.rM6_12, gt12: b.pol.rGt12 })) }); };
for (let i = 0; i < 6; i++) step();
W.addShock({ name: 'Khủng hoảng TPDN BĐS', left: 12, re: 2.5, reHeat: -1, dep: 2, demand: 0.85, ib: 1.0 }); W.macro.re -= 0.5; console.log(`[tháng 6] nổ khủng hoảng TPDN BĐS; TCV giữ ${W.sbv.refi}; huy động 3–6T hệ thống ${f(W.market.m6_12)}, ≥12T ${f(W.market.gt12)}`);
for (let i = 6; i < 48; i++) { step(); const r = rows[rows.length - 1]; if (formM == null && r.rs >= 5) formM = r.m; if (false) { const K = W.market; easeM = r.m; easeRef = { m6: K.m6_12, gt12: K.gt12, prem: W.depPrem() }; W.sbv.mltMax += 4; W.sbv.easeRef = { m: W.month, m6: K.m6_12, gt12: K.gt12, prem: W.depPrem() }; console.log(`[tháng 24] nới SFL: trần lên ${W.sbv.mltMax}%; phụ trội 3–6T ${f(easeRef.prem.m6)} ≥12T ${f(easeRef.prem.gt12)}; mặt bằng 3–6T ${f(K.m6_12)} ≥12T ${f(K.gt12)}`); } }
const at = mm => rows.find(r => r.m === mm);
console.log('tháng  cơ cấu%  3–6T   ≥12T   TCV   vay   nợ xấu'); for (const r of rows) if (r.m % 3 === 0) console.log(String(r.m).padStart(5), f(r.rs, 1).padStart(7), f(r.m6).padStart(6), f(r.gt12).padStart(6), f(r.refi).padStart(5), f(r.lend).padStart(5), f(r.npl, 1).padStart(6));
ok(formM != null, `1. dư nợ cơ cấu hệ thống ≥ 5% từ tháng ${formM} (${formM ? f(at(formM).rs, 1) : '-'}%)`);
if (formM != null) { const a = at(formM), b = at(formM + 6); ok(b && b.m6 - a.m6 >= 0.5 && b.refi === a.refi, `2. lãi 3–6T hệ thống ${f(a.m6)} → ${f(b && b.m6)} (+${f(b ? b.m6 - a.m6 : 0)}) sau 6 tháng, TCV giữ ${a.refi} (mục tiêu ≥ +0,5)`);
  const hi = a.banks.filter(x => x.rsSh >= 8).map(x => x.code); const sum6 = (code, k, from, to) => rows.filter(r => r.m > from && r.m <= to).reduce((acc, r) => acc + ((r.banks.find(x => x.code === code) || {})[k] || 0), 0);
  for (const code of hi) { const accr = sum6(code, 'accrM', formM, formM + 3), posB = sum6(code, 'selfPos', formM - 3, formM) / 3, posA = sum6(code, 'selfPos', formM, formM + 3) / 3, netB = sum6(code, 'net', formM - 3, formM), netA = sum6(code, 'net', formM, formM + 3);
    ok(accr > 0 && posA < posB, `3. ${code} (cơ cấu ${f(a.banks.find(x => x.code === code).rsSh, 1)}%): lãi dự thu 3 tháng ${Math.round(accr)} tỷ vào lợi nhuận (lãi ròng 3 tháng ${Math.round(netB)} → ${Math.round(netA)}), tiền tự có bình quân ${Math.round(posB)} → ${Math.round(posA)} (mục tiêu: dự thu > 0, tiền tự có giảm)`); } }
{ // hai ván cùng seed, không sốc, NHNN giữ TCV: tháng 12 siết SFL để nửa số ngân hàng sát trần (phụ trội ≥12T); ván A nới trần tháng 16, ván B (đối chứng) không nới; so thay đổi phụ trội 3–6T và ≥12T giữa hai ván sau 6 tháng
  const run = ease => { let s2 = 7; Math.random = () => { s2 = (s2 * 1103515245 + 12345) % 2147483648; return s2 / 2147483648; }; const W2 = new World('bank', 'vcb', 'real'); setW(W2); W2.weekly = true; W2.termMonths = 0; W2.sbv.holdRefi = true; const st2 = () => { W2.aiPolicy(W2.player); for (let k = 0; k < 4; k++) { W2.pendingEvent = null; W2.weekStep(); W2.pendingEvent = null; } };
    for (let i = 0; i < 12; i++) st2(); const mr = W2.banks.filter(b => !b.dead).map(b => b.mltRatio()).sort((x, y) => x - y); W2.sbv.mltMax = Math.max(8, Math.round(mr[Math.floor(mr.length / 2)]) + 1); const mlt0 = W2.sbv.mltMax;
    for (let i = 12; i < 16; i++) st2(); const K2 = W2.market; const ref = { m6: K2.m6_12, gt12: K2.gt12, prem: W2.depPrem(), tight: W2.banks.filter(b => !b.dead && b.mltRatio() > W2.sbv.mltMax - 2).length, mlt0 }; if (ease) { W2.sbv.mltMax += 4; W2.sbv.easeRef = { m: W2.month, m6: K2.m6_12, gt12: K2.gt12, prem: W2.depPrem() }; }
    for (let i = 16; i < 22; i++) st2(); return { ref, now: W2.depPrem(), K: W2.market, W: W2 }; };
  const A = run(true), B = run(false); const dA = { m6: A.now.m6 - A.ref.prem.m6, gt12: A.now.gt12 - A.ref.prem.gt12 }, dB = { m6: B.now.m6 - B.ref.prem.m6, gt12: B.now.gt12 - B.ref.prem.gt12 };
  console.log(`[hai ván cùng seed] siết SFL về ${A.ref.mlt0}% tháng 12 (${A.ref.tight} ngân hàng sát trần); ván A nới lên ${A.W.sbv.mltMax}% tháng 16, ván B giữ ${B.W.sbv.mltMax}%`);
  ok(dA.m6 - dB.m6 >= -0.2 && dA.gt12 - dB.gt12 < dA.m6 - dB.m6 - 0.1, `4. nới SFL so với đối chứng sau 6 tháng: phụ trội 3–6T ${f(dA.m6 - dB.m6, 2)} điểm (không giảm quá 0,2), phụ trội ≥12T ${f(dA.gt12 - dB.gt12, 2)} điểm (giảm nhiều hơn 3–6T ít nhất 0,1); mặt bằng ván A 3–6T ${f(A.K.m6_12)} ≥12T ${f(A.K.gt12)}, ván B 3–6T ${f(B.K.m6_12)} ≥12T ${f(B.K.gt12)}`);
  const sb2 = A.W.traceLog.filter(e => e.k === 'sbv' && /sau nới SFL/.test(e.t)).slice(-1)[0]; console.log('log sbv (ván A):', sb2 ? sb2.t.slice(sb2.t.indexOf('sau nới SFL'), sb2.t.indexOf('sau nới SFL') + 300) : 'KHÔNG CÓ'); setW(W); }
ok(Math.max(...rows.map(r => r.resid)) < 100 && Math.max(...rows.map(r => r.ledg)) < 100, `5. đồng nhất thức bảng cân đối lệch tối đa ${Math.round(Math.max(...rows.map(r => r.resid)))}, sổ tiền cơ sở lệch ${Math.round(Math.max(...rows.map(r => r.ledg)))} (ngưỡng 100)`);
{ const e = at(formM + 36), e1 = at(formM + 35); ok(e && e.rs < 1 && e.npl > e1.npl + 1, `6. kết thúc cơ cấu tháng ${formM + 36}: cơ cấu hệ thống ${f(e1 && e1.rs, 1)} → ${f(e && e.rs, 1)}%, nợ xấu ${f(e1 && e1.npl, 1)} → ${f(e && e.npl, 1)} (60% chuyển nhóm 3, thoái lãi dự thu)`); }
const sb = W.traceLog.filter(e => e.k === 'sbv' && /sau nới SFL/.test(e.t)).slice(-1)[0]; console.log('log sbv:', sb ? sb.t.slice(sb.t.indexOf('nợ cơ cấu hệ thống'), sb.t.indexOf('nợ cơ cấu hệ thống') + 260) : 'KHÔNG CÓ');
const cl = W.traceLog.filter(e => e.k === 'close' && /nợ cơ cấu/.test(e.t)).slice(-1)[0]; console.log('log close:', cl ? cl.t.slice(cl.t.indexOf('nợ cơ cấu'), cl.t.indexOf('nợ cơ cấu') + 220) : 'KHÔNG CÓ');
console.log(`\nĐạt ${pass}, trượt ${fail}`); process.exit(fail ? 1 : 0);
