// So sánh có/không TT50/2026 trên bảng cân đối hệ thống: node tools/tt50sim.js [SEED=1] [YEARS=5]
const fs = require('fs'); const html = fs.readFileSync(__dirname + '/../index.html', 'utf8');
const js = html.slice(html.indexOf('<script>') + 8, html.lastIndexOf('</script>')).replace('renderStart();', '');
global.window = { devicePixelRatio: 1, addEventListener() {}, scrollTo() {} }; global.document = { querySelector() { return { innerHTML: '', querySelectorAll() { return []; } }; }, getElementById() { return null; }, querySelectorAll() { return []; }, documentElement: {}, body: { appendChild() {}, classList: { add() {}, remove() {} } }, createElement() { return { style: {}, classList: { add() {}, remove() {} }, appendChild() {}, setAttribute() {}, getContext() { return null; } }; } }; global.localStorage = { getItem() { return null; }, setItem() {} }; global.navigator = { clipboard: {} }; global.requestAnimationFrame = () => 0; global.setTimeout = () => 0; global.console.warn = () => {};
const m = {}; new Function('module', js + ';module.exports={World,REG_CAL,setW:w=>{W=w;}};')(m); const { World, REG_CAL, setW } = m.exports;
const YEARS = +(process.env.YEARS || 5); const seed = +(process.env.SEED || 1); const f = (v, d = 1) => (v == null || !isFinite(v) ? '-' : (+v).toFixed(d));
const snap = W => { const al = W.banks.filter(b => !b.dead); const sum = a => a.reduce((x, y) => x + y, 0); const r = W.hist[W.hist.length - 1]; const K = W.market; const dep = sum(al.map(b => b.deposits())), L = sum(al.map(b => b.grossLoans())), TA = sum(al.map(b => b.totalAssets()));
  const nsfr = sum(al.map(b => b.nsfr().asf)) / Math.max(1, sum(al.map(b => b.nsfr().rsf))) * 100; const lcr = sum(al.map(b => b.lcr().hqla)) / Math.max(1, sum(al.map(b => { const L2 = b.lcr(); return L2.hqla / Math.max(1e-9, L2.lcr / 100); }))) * 100;
  return { d: W.dateStr(), loans: L / 1e6, deps: dep / 1e6, gb: sum(al.map(b => b.gbonds)) / 1e6, gtcg: sum(al.map(b => b.bonds + b.subBonds)) / 1e6, ib: sum(al.map(b => b.ibBorrow)) / 1e6, omo: sum(al.map(b => b.refi + (b.lolr || 0))) / 1e6, tre: sum(al.map(b => b.treasury || 0)) / 1e6, TA: TA / 1e6,
    ldrRaw: L / Math.max(1, dep) * 100, ldrReg: W.sysLdr(al), mlt: sum(al.map(b => b.mltLoans())) / Math.max(1, L) * 100, sfl: sum(al.map(b => Math.max(0, b.mltLoans() - b.mltSources()))) / Math.max(1, sum(al.map(b => b.shortSources()))) * 100, lcr, nsfr, gbTA: sum(al.map(b => b.gbonds)) / TA * 100, gt12: sum(al.map(b => b.dep.gt12)) / Math.max(1, dep) * 100,
    cg: r.cg, m2: r.m2, dep12: K.gt12, m6: K.m6_12, lend: K.lend, ibON: K.ibON, npl: r.npl, car: r.sysCar, nim: r.camels ? r.camels.nim : null, roa: r.camels ? r.camels.roa : null, cpi: r.cpi, gdp: r.gdp, tt50: al.filter(b => b.tt50).length, ldrAt: al.filter(b => b.ldr() > b.ldrCap() - 1).length, mltAt: al.filter(b => !b.tt50 && b.mltRatio() > W.sbv.mltMax - 2).length, fine: sum(al.map(b => b.fine || 0)) / 1e3, lolr: al.filter(b => b.lolr > 0).length, dead: W.banks.filter(b => b.dead).length, roomAvg: sum(al.map(b => b.room)) / al.length, lev: sum(al.map(b => b.tier1())) / Math.max(1, sum(al.map(b => b.totalAssets() + b.grossLoans() * 0.1))) * 100 }; };
const run = withTT50 => { let s = seed; Math.random = () => { s = (s * 1103515245 + 12345) % 2147483648; return s / 2147483648; }; const W = new World('bank', 'vcb', 'real'); setW(W); W.weekly = true; W.termMonths = 0; W.randomEvents = false;
  if (!withTT50) for (const r of REG_CAL) if (/^tt50/.test(r.id)) W.regApplied[r.id] = true; // phản thực: TT50 không bao giờ có hiệu lực, giữ TT22/TT26 mãi
  const out = []; for (let i = 0; i < YEARS * 12; i++) { W.aiPolicy(W.player); for (let k = 0; k < 4; k++) { W.pendingEvent = null; W.weekStep(); W.pendingEvent = null; } const d = W.dateStr(); if (/^T(12|6)\//.test(d) || d === 'T10/2028' || d === 'T11/2026') out.push(snap(W)); }
  return { W, out }; };
const A = run(true), B = run(false);
const cols = [['loans', 'dư nợ (tr tỷ)', 2], ['deps', 'tiền gửi', 2], ['gb', 'TPCP', 2], ['gtcg', 'GTCG+TP cấp 2', 2], ['ib', 'vay LNH', 2], ['omo', 'OMO+TCV đặc biệt', 2], ['ldrRaw', 'LDR thô L/D', 1], ['ldrReg', 'LDR quy định', 1], ['sfl', 'SFL hệ thống', 1], ['mlt', 'TDH/dư nợ', 1], ['gbTA', 'TPCP/TS', 1], ['gt12', 'TG ≥12T/TG', 1], ['lcr', 'LCR', 0], ['nsfr', 'NSFR', 0], ['lev', 'LEV', 1], ['cg', 'tín dụng yoy', 1], ['m2', 'M2 yoy', 1], ['dep12', 'lãi 12T', 2], ['m6', 'lãi 6–12T', 2], ['lend', 'lãi vay mới', 2], ['ibON', 'LNH O/N', 2], ['nim', 'NIM', 2], ['roa', 'ROA', 2], ['npl', 'nợ xấu', 2], ['car', 'CAR', 1], ['cpi', 'CPI', 1], ['gdp', 'GDP', 1], ['tt50', 'NH theo TT50', 0], ['ldrAt', 'NH sát trần LDR', 0], ['mltAt', 'NH sát trần SFL', 0], ['lolr', 'NH tái cấp vốn ĐB', 0], ['fine', 'tiền phạt lũy kế (tỷ)', 0], ['roomAvg', 'room bq', 1]];
console.log(`seed ${seed}, ${YEARS} năm, sự kiện ngẫu nhiên tắt, giai đoạn thật bật. A = có TT50, B = không TT50 (TT22/TT26 mãi)`);
console.log('chỉ tiêu'.padEnd(22) + A.out.map(o => o.d.padStart(16)).join(''));
for (const [k, name, d] of cols) { console.log(name.padEnd(22) + A.out.map((o, i) => (f(o[k], d) + '/' + f(B.out[i][k], d)).padStart(16)).join('')); }
console.log('\n(ô = có TT50 / không TT50)');
const last = A.out[A.out.length - 1], lastB = B.out[B.out.length - 1];
console.log('\nChênh cuối ván (A − B):', ['loans', 'deps', 'gb', 'gtcg', 'ldrReg', 'sfl', 'lcr', 'nsfr', 'cg', 'dep12', 'lend', 'nim', 'npl', 'car'].map(k => `${k} ${f(last[k] - lastB[k], 2)}`).join(', '));
const adopt = A.W.banks.filter(b => !b.dead).map(b => `${b.code} ${b.tt50 ? 'T' + (b.tt50M) : '–'} LDR ${f(b.ldr(), 1)}/${b.ldrCap()} LCR ${f(b.lcr().lcr, 0)} NSFR ${f(b.nsfr().nsfr, 0)} TDH ${f(b.mltLoans() / Math.max(1, b.grossLoans()) * 100, 0)}% ${b.ldrExempted ? 'MIỄN LDR' : ''}`); console.log('\nNgân hàng (A):', adopt.join(' · '));
const actsA = A.W.traceLog.filter(e => e.k === 'act' && /TT50|NSFR|LCR|LDR/.test(e.t)).map(e => e.t.slice(0, 150)); console.log('\n[act] liên quan TT50 ở A:', actsA.length); actsA.slice(0, 25).forEach(a => console.log('  ', a));
